package passwrod

//go:generate msgp

// PasswordEntry struct to layout the form for password entries
type PasswordEntry struct {
	Name string `msgpack:Name`
	Site string `msgpack:Site`
	Username string `msgpack:Username`
	Password string `msgpack:Password`
	Category string `msgpack:Category`
}

// EntryCategory for the vault entry
// type AutoGenerated struct {
// 	Category struct {
// 		Website struct {
// 			UserID    int    `json:"userId"`
// 			ID        int    `json:"id"`
// 			Title     string `json:"title"`
// 			Completed bool   `json:"completed"`
// 		} `json:"Website"`
// 	} `json:"Category"`
// }

// PasswordCategory struct
